import{readFileSync}from"node:fs";import{join}from"node:path";import{describe,expect,it}from"vitest";
const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8").toLowerCase();
const sql=read("supabase/migrations/20260803100000_fix_archived_school_permanent_deletion.sql");
describe("archived-school deletion reconciliation",()=>{
 it("identifies every direct schools foreign key at runtime",()=>{expect(sql).toContain("from pg_constraint");expect(sql).toContain("constraint_row.confrelid = 'public.schools'::regclass");expect(sql).toContain("public.school_setup_email_attempts");});
 it("explicitly detaches delivery attempts before deleting invitations and the school",()=>{const attempts=sql.indexOf("update public.school_setup_email_attempts"),drafts=sql.indexOf("delete from public.calendar_wizard_drafts"),invites=sql.indexOf("delete from public.pending_admin_invites"),school=sql.indexOf("delete from public.schools");expect(attempts).toBeGreaterThan(0);expect(drafts).toBeGreaterThan(attempts);expect(invites).toBeGreaterThan(drafts);expect(school).toBeGreaterThan(invites);});
 it("handles archived schools with drafts, invitations, assignments, and all supported children",()=>{for(const table of ["calendar_wizard_drafts","pending_admin_invites","school_memberships","calendar_days","periods","schedules","schedule_patterns","announcements","events","games","teams","sports","resources","notification_audit","school_timezone_audit","subscription_ledger_entries"])expect(sql).toContain(`public.${table}`);});
 it("preserves shared identities and authentication accounts",()=>{expect(sql).not.toContain("delete from auth.users");expect(sql).not.toContain("delete from public.users");expect(sql).toContain("update public.users");expect(sql).toContain("set school_id = null");});
 it("rejects active schools and unauthorized callers while permitting service-role maintenance",()=>{expect(sql).toContain("if v_school.archived_at is null");expect(sql).toContain("school_not_archived");expect(sql).toContain("current_user_is_super_admin");expect(sql).toContain("auth.jwt()->>'role'");expect(sql).toContain("to authenticated, service_role");expect(sql).toContain("from public;");});
 it("keeps database cleanup atomic and retryable after forced child failures",()=>{expect(sql).toContain("exception\n  when others then");expect(sql).toContain("status in ('database_pending', 'database_failed')");expect(sql).toContain("'database_failed'");expect(sql.indexOf("return jsonb_build_object(\n    'status', 'success'")).toBeGreaterThan(sql.indexOf("delete from public.schools"));});
 it("returns categorized safe diagnostics",()=>{expect(sql).toContain("remaining_dependencies");for(const field of ["returned_sqlstate","message_text","pg_exception_detail","pg_exception_hint","schema_name","table_name","column_name","constraint_name","pg_exception_context"])expect(sql).toContain(field);});
});
