import {readFileSync} from "node:fs";import {join} from "node:path";import {describe,expect,it} from "vitest";import {isValidTimeZone,PLATFORM_FEATURE_KEYS,validateGeneralSettings} from "./platformSettings";
const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");
describe("platform settings foundation",()=>{
 it("validates and normalizes the supported general fields",()=>{expect(validateGeneralSettings({support_email:"help@example.org",default_sender_name:"Sundial",support_website_url:"https://example.org",support_phone:"555-0100"})).toBeNull();expect(validateGeneralSettings({support_email:"bad",default_sender_name:"Sundial"})).toMatch(/email/i);expect(validateGeneralSettings({support_email:"help@example.org",default_sender_name:"x",support_website_url:"javascript:alert(1)"})).toMatch(/URL/i);expect(validateGeneralSettings({support_email:"help@example.org",default_sender_name:"x",support_phone:"x".repeat(41)})).toMatch(/40/);expect(validateGeneralSettings({support_email:"help@example.org",default_sender_name:"x",unknown:true})).toMatch(/unknown/i)});
 it("validates IANA timezones",()=>{expect(isValidTimeZone("America/Los_Angeles")).toBe(true);expect(isValidTimeZone("Mars/Olympus_Mons")).toBe(false)});
 it("uses a fixed feature allowlist",()=>{expect(PLATFORM_FEATURE_KEYS).toHaveLength(10);expect(PLATFORM_FEATURE_KEYS).not.toContain("billing" as never)});
 it("creates one seeded versioned settings record and immutable audit model",()=>{const sql=read("supabase/migrations/20260720150000_platform_settings_foundation.sql");expect(sql).toContain("id boolean primary key");expect(sql).toContain("on conflict (id) do nothing");expect(sql).toContain("version bigint not null");expect(sql).toContain("platform_settings_audit");expect(sql).not.toContain("policy \"SchoolAdmins read platform settings\"")});
 it("enforces SuperAdmin RLS and server-derived actors",()=>{const sql=read("supabase/migrations/20260720150000_platform_settings_foundation.sql");expect(sql.match(/current_user_is_super_admin\(\)/g)?.length).toBeGreaterThanOrEqual(5);expect(sql).toContain("v_actor uuid := auth.uid()");expect(sql).toContain("revoke all on public.platform_settings")});
 it("applies defaults atomically only during new school creation",()=>{const sql=read("supabase/migrations/20260720150000_platform_settings_foundation.sql");const action=read("src/app/admin/dashboard/schools/actions.ts");expect(sql).toContain("create_school_with_platform_defaults");expect(sql).toContain("insert into public.school_feature_availability");expect(action).toContain('rpc("create_school_with_platform_defaults"');expect(action).not.toContain('timezone: "America/Los_Angeles"');expect(sql).not.toMatch(/update public\.schools[\s\S]*school_feature_availability/)});
 it("keeps welcome-first setup and ignores browser feature values",()=>{const sql=read("supabase/migrations/20260720150000_platform_settings_foundation.sql");const action=read("src/app/admin/dashboard/schools/actions.ts");expect(sql).toContain("'welcome'");expect(action).not.toContain("feature_");expect(sql).toContain("from public.platform_feature_defaults")});
 it("guards stale writes and writes successful audit entries in the transaction",()=>{const sql=read("supabase/migrations/20260720150000_platform_settings_foundation.sql");expect(sql).toContain("v_version <> p_expected_version");expect(sql).toContain("for update");expect(sql.indexOf("update public.platform_settings")).toBeLessThan(sql.indexOf("insert into public.platform_settings_audit"))});
});
