import {readFileSync} from "node:fs";import {join} from "node:path";import {describe,expect,it} from "vitest";
const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");
describe("SuperAdmin school setup email provider contract",()=>{
 const migration=read("supabase/migrations/20260802120000_school_setup_email_provider.sql"),actions=read("src/app/admin/dashboard/settings/actions.ts"),page=read("src/app/admin/dashboard/settings/page.tsx"),form=read("src/app/admin/dashboard/settings/EmailDeliveryForm.tsx"),delivery=read("src/lib/email/schoolSetupDelivery.server.ts"),providers=read("src/lib/email/schoolSetupProviders.server.ts");
 it("defaults safely to Resend and accepts only the provider enum",()=>{expect(migration).toContain("default 'resend'");expect(migration).toContain("('google_workspace','resend')");expect(actions).toContain("isSchoolSetupEmailProvider(provider)");expect(form).not.toContain('name="from"');});
 it("retains SuperAdmin authorization, concurrency, and immutable setting audits",()=>{expect(actions.match(/requireSuperAdminAccess\(\)/g)?.length).toBeGreaterThanOrEqual(4);expect(migration).toContain("for update");expect(migration).toContain("v_version<>p_expected_version");expect(migration).toContain("correlation_id");});
 it("shows active identity, configuration, change metadata, confirmation and test result",()=>{for(const text of ["Active provider","Active From address","Reply-To address","Configuration status","Last changed","Last changed by","Send test email","Provider message ID","Existing invitations are not affected."])expect(form).toContain(text);expect(page).toContain('key:"email"');});
 it("uses one provider abstraction for every existing invitation flow without fallback",()=>{expect(delivery).toContain("sendSchoolSetupEmail(provider");expect(providers).not.toMatch(/fallback/i);for(const path of ["src/app/admin/dashboard/schools/actions.ts","src/app/admin/dashboard/schools/invitation-actions.ts","src/app/admin/dashboard/users/actions.ts"])expect(read(path)).toContain("deliverSchoolSetupInvitation");});
 it("records normalized invitation attempt fields without token material",()=>{for(const column of ["invitation_id","school_id","recipient","provider","from_address","provider_message_id","sent_at","status","error_code","error_message"])expect(migration).toContain(column);expect(migration.match(/school_setup_email_attempts[\s\S]*/)?.[0]).not.toContain("invite_token");});
 it("keeps Email Delivery server-action modules free of non-action exports",()=>{for(const path of ["src/app/admin/dashboard/settings/actions.ts","src/app/admin/dashboard/schools/invitation-actions.ts","src/app/admin/invitations/actions.ts"]){const source=read(path);expect(source).toMatch(/^"use server";/);expect(source).not.toMatch(/^export\s+(?!async\s+function)/m);}});
 it("submits only the canonical provider field and controlled enum values",()=>{expect(form).toContain('name="school_setup_email_provider"');expect(form).not.toMatch(/name="(?:schoolSetupEmailProvider|setup_email_provider|email_provider|school_setup_provider|settingName|setting_key)"/);expect(form).toContain('(["google_workspace","resend"] as const)');expect(actions).toContain('new Set(["school_setup_email_provider","version"])');expect(actions).toContain('key.startsWith("$ACTION_")');});
});
