import {readFileSync} from "node:fs";import {join} from "node:path";import {describe,expect,it} from "vitest";const read=(p:string)=>readFileSync(join(process.cwd(),p),"utf8");const sql=read("supabase/migrations/20260720170000_subscriptions_foundation.sql");
describe("subscriptions migration and security contract",()=>{
 it("seeds stable plan templates idempotently at the required prices",()=>{expect(sql).toContain("('pilot','Pilot','Complimentary pilot plan',0,0,false,false)");expect(sql).toContain("('founder','Founder','Limited Founder School contract',250000,150000,true,true)");expect(sql).toContain("('standard','Standard','Standard annual school plan',500000,250000,true,false)");expect(sql).toContain("on conflict (code) do nothing")});
 it("stores integer cents and snapshots contracted prices",()=>{expect(sql).toContain("contracted_setup_fee_cents bigint");expect(sql).toContain("contracted_annual_price_cents bigint");expect(sql).not.toMatch(/numeric\s*\(|double precision|real\b/i)});
 it("allocates permanent founder claims 1 through 5 without browser slots",()=>{expect(sql).toContain("create table if not exists public.founder_slot_claims");expect(sql).toContain("slot smallint primary key check (slot between 1 and 5)");expect(sql).toContain("generate_series(1,5)");expect(sql).toContain("select * into v_plan from public.subscription_plans where code=p_plan_code for update");expect(sql).not.toContain("p_founder_slot")});
 it("retains billing records and blocks school cascade deletion",()=>{expect(sql.match(/references public\.schools\(id\) on delete restrict/g)?.length).toBeGreaterThanOrEqual(3);expect(sql).not.toContain("on delete cascade");expect(sql).not.toMatch(/delete from public\.subscription_/)});
 it("enforces one current subscription per school and stale versions",()=>{expect(sql).toContain("school_id uuid not null unique");expect(sql).toContain("v_before.version<>p_expected_version");expect(sql).toContain("version=version+1")});
 it("makes ledger writes idempotent and actor-derived",()=>{expect(sql).toContain("subscription_ledger_idempotency_idx");expect(sql).toContain("v_actor uuid:=auth.uid()");expect(sql).toContain("idempotent',true");expect(sql).toContain("amount_cents bigint not null check (amount_cents > 0)")});
 it("denies application writes except through SuperAdmin RPCs",()=>{expect(sql.match(/current_user_is_super_admin\(\)/g)?.length).toBeGreaterThanOrEqual(8);expect(sql).toContain("revoke all on public.subscription_plans");expect(sql).toContain("grant select on public.subscription_plans");expect(sql).not.toContain("grant insert on public.subscription_ledger_entries to authenticated")});
 it("keeps subscription status separate from school lifecycle",()=>{expect(sql).not.toMatch(/update public\.schools\s+set\s+(archived_at|is_active)/);expect(sql).not.toMatch(/update public\.school_subscriptions[\s\S]*archived_at/)});
});
