import {describe,expect,it} from "vitest";import {calculateSubscriptionOverview,ledgerBalance,parseUsdToCents,pastDueBalance,setupFeesCollected,validDateRange,type LedgerEntry,type SubscriptionSummaryInput} from "./subscriptions";
const sub=(overrides:Partial<SubscriptionSummaryInput>={}):SubscriptionSummaryInput=>({plan_code:"standard",status:"active",contracted_annual_price_cents:250000,next_renewal_date:"2026-09-01",billing_contact_email:"billing@example.org",...overrides});
const entry=(overrides:Partial<LedgerEntry>={}):LedgerEntry=>({subscription_id:"one",entry_type:"annual_charge",direction:"debit",amount_cents:10000,status:"pending",due_date:"2026-01-01",...overrides});
describe("subscription financial calculations",()=>{
 it("parses USD into integer cents without floating point storage",()=>{expect(parseUsdToCents("2500.00")).toBe(250000);expect(parseUsdToCents("1.5")).toBe(150);expect(parseUsdToCents("-1")).toBeNull();expect(parseUsdToCents("1.999")).toBeNull()});
 it("calculates charges, credits, refunds, waivers, and voids",()=>{expect(ledgerBalance([entry(),entry({entry_type:"payment",direction:"credit",amount_cents:4000,status:"paid"}),entry({entry_type:"waiver",direction:"credit",amount_cents:1000,status:"waived"}),entry({entry_type:"refund",direction:"debit",amount_cents:500,status:"refunded"}),entry({amount_cents:999,status:"voided"})])).toBe(5500)});
 it("calculates authoritative past-due balance per subscription after credits",()=>{expect(pastDueBalance([entry(),entry({entry_type:"payment",direction:"credit",amount_cents:3000,status:"paid",due_date:null}),entry({subscription_id:"two",amount_cents:5000})],"2026-07-20")).toBe(12000)});
 it("counts only paid setup fees and subtracts refunds",()=>{expect(setupFeesCollected([entry({entry_type:"setup_fee_charge",status:"paid",amount_cents:250000}),entry({entry_type:"setup_fee_charge",status:"pending",amount_cents:500000}),entry({entry_type:"refund",direction:"debit",status:"refunded",amount_cents:50000})])).toBe(200000)});
 it("separates pilots and excludes canceled contracts from ARR",()=>{const result=calculateSubscriptionOverview([sub(),sub({plan_code:"pilot",contracted_annual_price_cents:0}),sub({plan_code:"custom",contracted_annual_price_cents:900000}),sub({status:"canceled",contracted_annual_price_cents:999999})],[],"2026-07-20");expect(result.activePaidSchools).toBe(2);expect(result.pilotSchools).toBe(1);expect(result.annualRecurringRevenueCents).toBe(1150000)});
 it("validates calendar-date ordering",()=>{expect(validDateRange("2026-01-01","2027-01-01")).toBe(true);expect(validDateRange("2027-01-01","2026-01-01")).toBe(false)});
});
