export const PLAN_CODES=["pilot","founder","standard","custom"] as const;
export const SUBSCRIPTION_STATUSES=["pending","active","past_due","paused","canceled"] as const;
export const LEDGER_TYPES=["setup_fee_charge","annual_charge","custom_charge","payment","waiver","refund","adjustment"] as const;
export type PlanCode=typeof PLAN_CODES[number];export type SubscriptionStatus=typeof SUBSCRIPTION_STATUSES[number];export type LedgerType=typeof LEDGER_TYPES[number];
export type SubscriptionSummaryInput={plan_code:PlanCode;status:SubscriptionStatus;contracted_annual_price_cents:number;next_renewal_date:string|null;billing_contact_email:string|null};
export type LedgerEntry={subscription_id?:string;entry_type:LedgerType;direction:"debit"|"credit";amount_cents:number;status:"pending"|"paid"|"past_due"|"waived"|"refunded"|"voided";due_date:string|null;effective_date?:string|null};
export function formatUsd(cents:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100)}
export function parseUsdToCents(value:string){const match=value.trim().match(/^\$?(\d{1,10})(?:\.(\d{1,2}))?$/);if(!match)return null;const cents=Number(match[1])*100+Number((match[2]||"").padEnd(2,"0"));return Number.isSafeInteger(cents)?cents:null}
export function ledgerBalance(entries:LedgerEntry[]){return entries.filter(e=>e.status!=="voided"&&(e.status!=="refunded"||e.entry_type==="refund")).reduce((sum,e)=>sum+(e.direction==="debit"?e.amount_cents:-e.amount_cents),0)}
export function pastDueBalance(entries:LedgerEntry[],today:string){const groups=new Map<string,LedgerEntry[]>();for(const entry of entries){const key=entry.subscription_id||"all";groups.set(key,[...(groups.get(key)||[]),entry])}return [...groups.values()].reduce((total,group)=>{const overdue=group.filter(e=>e.direction==="debit"&&["pending","past_due"].includes(e.status)&&Boolean(e.due_date&&e.due_date<today)).reduce((sum,e)=>sum+e.amount_cents,0);const credits=group.filter(e=>e.direction==="credit"&&!(["voided","refunded"] as string[]).includes(e.status)).reduce((sum,e)=>sum+e.amount_cents,0);return total+Math.max(0,overdue-credits)},0)}
export function setupFeesCollected(entries:LedgerEntry[]){const setupCharges=entries.filter(e=>e.entry_type==="setup_fee_charge"&&e.status==="paid").reduce((sum,e)=>sum+e.amount_cents,0);const refunds=entries.filter(e=>e.entry_type==="refund"&&e.status!=="voided").reduce((sum,e)=>sum+e.amount_cents,0);return Math.max(0,setupCharges-refunds)}
export function calculateSubscriptionOverview(subscriptions:SubscriptionSummaryInput[],ledger:LedgerEntry[],today:string,renewalDays=90){const end=new Date(`${today}T00:00:00Z`);end.setUTCDate(end.getUTCDate()+renewalDays);const endDate=end.toISOString().slice(0,10);return{activePaidSchools:subscriptions.filter(s=>s.status==="active"&&s.plan_code!=="pilot"&&s.contracted_annual_price_cents>0).length,pilotSchools:subscriptions.filter(s=>s.status!=="canceled"&&s.plan_code==="pilot").length,annualRecurringRevenueCents:subscriptions.filter(s=>s.status==="active"&&s.plan_code!=="pilot").reduce((sum,s)=>sum+s.contracted_annual_price_cents,0),setupFeesCollectedCents:setupFeesCollected(ledger),upcomingRenewals:subscriptions.filter(s=>s.status==="active"&&Boolean(s.next_renewal_date&&s.next_renewal_date>=today&&s.next_renewal_date<=endDate)).length,pastDueBalanceCents:pastDueBalance(ledger,today),missingBillingContacts:subscriptions.filter(s=>s.status==="active"&&!s.billing_contact_email).length,missingRenewalDates:subscriptions.filter(s=>s.status==="active"&&s.plan_code!=="pilot"&&!s.next_renewal_date).length}}
export function validDateRange(start:string|null,renewal:string|null){return !start||!renewal||renewal>start}
export function isUuid(value:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)}
