import Link from "next/link";
import SchoolAppInstallLink from "@/components/pwa/SchoolAppInstallLink";
import SchoolLogo from "@/components/SchoolLogo";
import SportIcon from "@/components/SportIcon";
import { PublicContainer, PublicEmptyState, SectionHeading } from "@/components/public-site/PublicSite";
import { publicDensity } from "@/components/public-site/publicDensity";
import { formatGameDateTime } from "@/lib/athletics";
import { loadPublicHomepage } from "@/lib/publicSite";
import { safePublicUrl } from "@/lib/publicUrl";
import { formatPeriodTime } from "@/lib/scheduleTime";
import { formatTimestampDateInTimeZone } from "@/lib/timezones";

function friendlyDate(value: string, options: Intl.DateTimeFormatOptions) { return new Date(`${value}T12:00:00`).toLocaleDateString("en-US", options); }
function eventTime(time: string | null) { return time ? formatPeriodTime(time) : "All day"; }
function summary(value: string | null, max = 180) { const text = (value || "").trim(); return text.length > max ? `${text.slice(0, max).trim()}…` : text; }

export default async function SchoolPage({ params }: { params: Promise<{ school: string }> }) {
  const { school: slug } = await params;
  const data = await loadPublicHomepage(slug);
  const { school, scheduleState } = data;
  const statusCopy = !data.day ? "Today’s calendar has not been published yet." : data.day.is_school_day === false ? (data.day.label || "No school today") : !data.schedule ? "Today’s bell times have not been published yet." : scheduleState.status === "needs_times" || scheduleState.status === "no_schedule" ? "Today’s bell times have not been published yet." : scheduleState.status === "in_period" ? `${scheduleState.currentPeriod?.name} is in session` : scheduleState.status === "passing" ? `Next: ${scheduleState.nextPeriod?.name}` : scheduleState.status === "before_school" ? `School begins with ${scheduleState.nextPeriod?.name}` : "The school day is complete";

  return <main className="overflow-hidden">
    <section className="relative isolate overflow-hidden bg-slate-950 text-white"><div aria-hidden="true" className="absolute inset-0 opacity-80" style={{ background: `radial-gradient(circle at 80% 20%, ${school.secondary_color || school.primary_color || "#64748b"}99, transparent 32%), radial-gradient(circle at 10% 85%, ${school.primary_color || "#2563eb"}aa, transparent 40%)` }} /><div aria-hidden="true" className="absolute inset-0 bg-[linear-gradient(120deg,rgba(255,255,255,.06)_1px,transparent_1px)] bg-[size:32px_32px] opacity-30" />
      <PublicContainer className="relative grid items-center gap-6 py-9 sm:py-11 lg:min-h-[29rem] lg:grid-cols-[1fr_auto] lg:gap-8 lg:py-16"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-white/70 sm:text-sm sm:tracking-[.2em]">{friendlyDate(data.today, { weekday: "long", month: "long", day: "numeric" })}</p><h1 className="mt-3 break-words text-[clamp(2.2rem,10vw,5.5rem)] font-black leading-[.95] tracking-[-.05em] sm:mt-4 lg:leading-[.93] lg:tracking-[-.055em]">{school.name}</h1><p className="mt-3 max-w-2xl text-base text-white/80 sm:mt-5 sm:text-lg">{school.mascot ? `Home of the ${school.mascot}` : school.district_name || "Welcome to our school community."}</p><div className="mt-5 flex flex-wrap gap-2.5 sm:mt-7"><Link href={`/${slug}/schedule`} className="inline-flex min-h-11 items-center rounded-full bg-white px-5 text-sm font-black text-slate-950 transition hover:-translate-y-0.5">View Calendar</Link><SchoolAppInstallLink href={`/${slug}/app`} className="inline-flex min-h-11 items-center rounded-full border border-white/30 bg-white/10 px-5 text-sm font-black backdrop-blur transition hover:bg-white/20">Open School App</SchoolAppInstallLink></div></div><SchoolLogo schoolName={school.name} logoUrl={school.logo_url} variant="preview" className="hidden h-40 w-40 rounded-[2rem] bg-white/95 p-4 shadow-2xl lg:grid" /></PublicContainer>
      <div aria-hidden="true" className="h-6 sm:hidden" />
    </section>

    <PublicContainer className="relative -mt-6 z-10"><section aria-labelledby="today-heading" className="rounded-[1.75rem] border border-slate-200/80 bg-white p-5 shadow-xl shadow-slate-900/10 dark:border-white/10 dark:bg-[#1b1e21] sm:p-6"><div className="grid gap-4 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--school-primary)]">Today at school</p><h2 id="today-heading" className="mt-1.5 text-xl font-black sm:text-2xl">{data.day?.label || data.schedule?.schedule_name || friendlyDate(data.today, { weekday: "long" })}</h2><p className="mt-1.5 text-slate-600 dark:text-slate-300">{statusCopy}</p></div>{scheduleState.currentPeriod && <div className="rounded-2xl bg-slate-100 px-4 py-3 dark:bg-white/[.06]"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Current period</p><p className="mt-1 font-black">{scheduleState.currentPeriod.name}</p><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{formatPeriodTime(scheduleState.currentPeriod.start_time)} – {formatPeriodTime(scheduleState.currentPeriod.end_time)}</p></div>}</div></section></PublicContainer>

    <div className="py-12 sm:py-14"><PublicContainer className={publicDensity.sectionStack}>
      {data.resources.length > 0 && <section><SectionHeading eyebrow="Explore" title="Quick links" href={data.resources.length > 8 ? `/${slug}/resources` : undefined} linkLabel="View all resources" /><div className={`grid grid-cols-2 max-[340px]:grid-cols-1 lg:grid-cols-4 ${publicDensity.grid}`}>{data.resources.slice(0, 8).map((resource) => { const href = safePublicUrl(resource.url) || safePublicUrl(resource.file_url); return href && <a key={resource.id} href={href} target="_blank" rel="noreferrer" className={`group min-h-24 rounded-2xl bg-white shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1 hover:shadow-md dark:bg-[#1b1e21] dark:ring-white/10 ${publicDensity.card}`}><p className="text-xs font-bold uppercase tracking-wider text-[var(--school-primary)]">{resource.category || "Resource"}</p><p className="mt-1.5 break-words font-black">{resource.title} <span aria-label="Opens in a new tab" className="text-slate-400">↗</span></p>{resource.description && <p className="mt-1.5 text-sm text-slate-500 dark:text-slate-400">{summary(resource.description, 70)}</p>}</a>; })}</div></section>}
      <section><SectionHeading eyebrow="Latest" title="Announcements" href={`/${slug}/announcements`} linkLabel="View all announcements" />{data.announcements.length ? <div className={`grid lg:grid-cols-2 ${publicDensity.grid}`}>{data.announcements.map((item) => <article key={item.id} className={`rounded-3xl bg-white shadow-sm ring-1 ring-slate-200 dark:bg-[#1b1e21] dark:ring-white/10 ${publicDensity.card}`}><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-500"><span>{item.priority ? "Featured" : "School news"}</span><span aria-hidden="true">•</span><time>{formatTimestampDateInTimeZone(new Date(item.publish_at), data.school.timezone || "America/Los_Angeles")}</time></div><h3 className="mt-2 text-lg font-black">{item.title}</h3><p className="mt-2 leading-6 text-slate-600 dark:text-slate-300">{summary(item.body)}</p></article>)}</div> : <PublicEmptyState>No announcements have been posted yet.</PublicEmptyState>}</section>
      <section><SectionHeading eyebrow="Save the date" title="Upcoming events" href={`/${slug}/events`} linkLabel="View all events" />{data.events.length ? <div className={`grid md:grid-cols-2 ${publicDensity.grid}`}>{data.events.map((event) => <article key={event.id} className={`flex rounded-3xl bg-white shadow-sm ring-1 ring-slate-200 dark:bg-[#1b1e21] dark:ring-white/10 ${publicDensity.card} gap-4`}><time className="grid h-16 w-14 shrink-0 place-content-center rounded-2xl bg-[var(--school-primary)] text-center text-[var(--school-primary-text)]"><span className="text-xs font-black uppercase">{friendlyDate(event.event_date, { month: "short" })}</span><span className="text-xl font-black leading-none">{friendlyDate(event.event_date, { day: "numeric" })}</span></time><div><h3 className="font-black">{event.title}</h3><p className="mt-1.5 text-sm text-slate-600 dark:text-slate-300">{eventTime(event.start_time)}{event.location ? ` · ${event.location}` : ""}</p></div></article>)}</div> : <PublicEmptyState>No upcoming events are posted right now.</PublicEmptyState>}</section>
      {data.games.length > 0 && <section><SectionHeading eyebrow="School spirit" title="Upcoming athletics" href={`/${slug}/app/athletics`} linkLabel="View athletics" /><div className={`grid md:grid-cols-2 lg:grid-cols-4 ${publicDensity.grid}`}>{data.games.map((game) => <article key={game.id} className={`rounded-3xl bg-white shadow-sm ring-1 ring-slate-200 dark:bg-[#1b1e21] dark:ring-white/10 ${publicDensity.card}`}><div className="grid h-11 w-11 place-items-center rounded-2xl bg-slate-100 dark:bg-white/[.06]"><SportIcon icon={game.sport?.icon} color={game.sport?.icon_color} /></div><h3 className="mt-3 font-black">{game.team?.name || "Team"} vs {game.opponent}</h3><p className="mt-1.5 text-sm text-slate-600 dark:text-slate-300">{formatGameDateTime(game.game_date)}</p><p className="mt-1 text-xs font-bold uppercase tracking-wider text-slate-500">{game.is_home ? "Home" : "Away"}{game.location ? ` · ${game.location}` : ""}</p></article>)}</div></section>}
    </PublicContainer></div>
  </main>;
}
