import Link from "next/link";
import SchoolLogo from "@/components/SchoolLogo";
import SportIcon from "@/components/SportIcon";
import { PublicContainer, PublicEmptyState, SectionHeading } from "@/components/public-site/PublicSite";
import { formatGameDateTime } from "@/lib/athletics";
import { loadPublicHomepage } from "@/lib/publicSite";
import { safePublicUrl } from "@/lib/publicUrl";
import { formatPeriodTime } from "@/lib/scheduleTime";

function friendlyDate(value: string, options: Intl.DateTimeFormatOptions) { return new Date(`${value}T12:00:00`).toLocaleDateString("en-US", options); }
function eventTime(time: string | null) { return time ? formatPeriodTime(time) : "All day"; }
function summary(value: string | null, max = 180) { const text = (value || "").trim(); return text.length > max ? `${text.slice(0, max).trim()}…` : text; }

export default async function SchoolPage({ params }: { params: Promise<{ school: string }> }) {
  const { school: slug } = await params;
  const data = await loadPublicHomepage(slug);
  const { school, scheduleState } = data;
  const statusCopy = !data.day ? "Today’s calendar has not been published yet." : data.day.is_school_day === false ? (data.day.label || "No school today") : !data.schedule ? "Today’s bell times have not been published yet." : scheduleState.status === "needs_times" || scheduleState.status === "no_schedule" ? "Today’s bell times have not been published yet." : scheduleState.status === "in_period" ? `${scheduleState.currentPeriod?.name} is in session` : scheduleState.status === "passing" ? `Next: ${scheduleState.nextPeriod?.name}` : scheduleState.status === "before_school" ? `School begins with ${scheduleState.nextPeriod?.name}` : "The school day is complete";

  return <main className="overflow-hidden">
    <section className="relative isolate overflow-hidden bg-slate-950 text-white"><div aria-hidden="true" className="absolute inset-0 opacity-80" style={{ background: `radial-gradient(circle at 80% 20%, ${school.secondary_color || school.primary_color || "#64748b"}99, transparent 32%), radial-gradient(circle at 10% 85%, ${school.primary_color || "#2563eb"}aa, transparent 40%)` }} /><div aria-hidden="true" className="absolute inset-0 bg-[linear-gradient(120deg,rgba(255,255,255,.06)_1px,transparent_1px)] bg-[size:32px_32px] opacity-30" />
      <PublicContainer className="relative grid items-center gap-7 py-10 sm:py-14 lg:min-h-[34rem] lg:grid-cols-[1fr_auto] lg:gap-10 lg:py-24"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-white/70 sm:text-sm sm:tracking-[.2em]">{friendlyDate(data.today, { weekday: "long", month: "long", day: "numeric" })}</p><h1 className="mt-3 break-words text-[clamp(2.35rem,11vw,6.5rem)] font-black leading-[.95] tracking-[-.05em] sm:mt-5 lg:leading-[.93] lg:tracking-[-.055em]">{school.name}</h1><p className="mt-4 max-w-2xl text-base text-white/80 sm:mt-6 sm:text-xl">{school.mascot ? `Home of the ${school.mascot}` : school.district_name || "Welcome to our school community."}</p><div className="mt-6 flex flex-wrap gap-3 sm:mt-9"><Link href={`/${slug}/schedule`} className="inline-flex min-h-12 items-center rounded-full bg-white px-5 text-sm font-black text-slate-950 transition hover:-translate-y-0.5 sm:px-6">View Calendar</Link><Link href={`/${slug}/app`} className="inline-flex min-h-12 items-center rounded-full border border-white/30 bg-white/10 px-5 text-sm font-black backdrop-blur transition hover:bg-white/20 sm:px-6">Open School App</Link></div></div><SchoolLogo schoolName={school.name} logoUrl={school.logo_url} variant="preview" className="hidden h-48 w-48 rounded-[2.5rem] bg-white/95 p-5 shadow-2xl lg:grid" /></PublicContainer>
    </section>

    <PublicContainer className="relative -mt-8 z-10"><section aria-labelledby="today-heading" className="rounded-[2rem] border border-slate-200/80 bg-white p-6 shadow-xl shadow-slate-900/10 dark:border-white/10 dark:bg-[#1b1e21] sm:p-8"><div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--school-primary)]">Today at school</p><h2 id="today-heading" className="mt-2 text-2xl font-black sm:text-3xl">{data.day?.label || data.schedule?.schedule_name || friendlyDate(data.today, { weekday: "long" })}</h2><p className="mt-2 text-slate-600 dark:text-slate-300">{statusCopy}</p></div>{scheduleState.currentPeriod && <div className="rounded-2xl bg-slate-100 px-5 py-4 dark:bg-white/[.06]"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Current period</p><p className="mt-1 font-black">{scheduleState.currentPeriod.name}</p><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{formatPeriodTime(scheduleState.currentPeriod.start_time)} – {formatPeriodTime(scheduleState.currentPeriod.end_time)}</p></div>}</div></section></PublicContainer>

    <div className="py-16 sm:py-20"><PublicContainer className="space-y-20">
      {data.resources.length > 0 && <section><SectionHeading eyebrow="Explore" title="Quick links" href={data.resources.length > 8 ? `/${slug}/resources` : undefined} linkLabel="View all resources" /><div className="grid grid-cols-2 gap-3 max-[340px]:grid-cols-1 lg:grid-cols-4">{data.resources.slice(0, 8).map((resource) => { const href = safePublicUrl(resource.url) || safePublicUrl(resource.file_url); return href && <a key={resource.id} href={href} target="_blank" rel="noreferrer" className="group min-h-28 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1 hover:shadow-md dark:bg-[#1b1e21] dark:ring-white/10 sm:p-5"><p className="text-xs font-bold uppercase tracking-wider text-[var(--school-primary)]">{resource.category || "Resource"}</p><p className="mt-2 break-words font-black">{resource.title} <span aria-label="Opens in a new tab" className="text-slate-400">↗</span></p>{resource.description && <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{summary(resource.description, 70)}</p>}</a>; })}</div></section>}
      <section><SectionHeading eyebrow="Latest" title="Announcements" href={`/${slug}/announcements`} linkLabel="View all announcements" />{data.announcements.length ? <div className="grid gap-5 lg:grid-cols-2">{data.announcements.map((item) => <article key={item.id} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200 dark:bg-[#1b1e21] dark:ring-white/10"><div className="flex items-center gap-3 text-xs font-bold uppercase tracking-wider text-slate-500"><span>{item.priority ? "Featured" : "School news"}</span><span aria-hidden="true">•</span><time>{new Date(item.publish_at).toLocaleDateString()}</time></div><h3 className="mt-3 text-xl font-black">{item.title}</h3><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">{summary(item.body)}</p></article>)}</div> : <PublicEmptyState>No announcements have been posted yet.</PublicEmptyState>}</section>
      <section><SectionHeading eyebrow="Save the date" title="Upcoming events" href={`/${slug}/events`} linkLabel="View all events" />{data.events.length ? <div className="grid gap-4 md:grid-cols-2">{data.events.map((event) => <article key={event.id} className="flex gap-5 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 dark:bg-[#1b1e21] dark:ring-white/10"><time className="grid h-20 w-16 shrink-0 place-content-center rounded-2xl bg-[var(--school-primary)] text-center text-[var(--school-primary-text)]"><span className="text-xs font-black uppercase">{friendlyDate(event.event_date, { month: "short" })}</span><span className="text-2xl font-black leading-none">{friendlyDate(event.event_date, { day: "numeric" })}</span></time><div><h3 className="font-black">{event.title}</h3><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{eventTime(event.start_time)}{event.location ? ` · ${event.location}` : ""}</p></div></article>)}</div> : <PublicEmptyState>No upcoming events are posted right now.</PublicEmptyState>}</section>
      {data.games.length > 0 && <section><SectionHeading eyebrow="School spirit" title="Upcoming athletics" href={`/${slug}/app/athletics`} linkLabel="View athletics" /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{data.games.map((game) => <article key={game.id} className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 dark:bg-[#1b1e21] dark:ring-white/10"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-slate-100 dark:bg-white/[.06]"><SportIcon icon={game.sport?.icon} color={game.sport?.icon_color} /></div><h3 className="mt-4 font-black">{game.team?.name || "Team"} vs {game.opponent}</h3><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{formatGameDateTime(game.game_date)}</p><p className="mt-1 text-xs font-bold uppercase tracking-wider text-slate-500">{game.is_home ? "Home" : "Away"}{game.location ? ` · ${game.location}` : ""}</p></article>)}</div></section>}
    </PublicContainer></div>
  </main>;
}
