export const aiCalendarImportJsonSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    documentTitle: { type: ["string", "null"] },
    detectedSchoolName: { type: ["string", "null"] },
    schoolYearLabel: { type: ["string", "null"] },
    firstInstructionalDate: { type: "string" },
    lastInstructionalDate: { type: "string" },
    operatingWeekdays: {
      type: "array",
      items: { type: "integer", minimum: 0, maximum: 6 },
    },
    expectedInstructionalDayCount: { type: ["integer", "null"], minimum: 0 },
    schoolYearConfidence: { enum: ["high", "review", "uncertain"] },
    detectedSchedules: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          tempId: { type: "string" },
          name: { type: "string" },
          category: {
            enum: ["regular", "rotation", "special", "finals", "minimum", "testing", "unknown"],
          },
          confidence: { enum: ["high", "review", "uncertain"] },
          evidence: { $ref: "#/$defs/evidence" },
        },
        required: ["tempId", "name", "category", "confidence", "evidence"],
      },
    },
    normalPattern: {
      type: "object",
      additionalProperties: false,
      properties: {
        type: { enum: ["same", "repeating", "weekday"] },
        scheduleTempIds: { type: "array", items: { type: "string" } },
        weekdayMappings: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              weekday: { type: "integer", minimum: 0, maximum: 6 },
              scheduleTempId: { type: "string" },
            },
            required: ["weekday", "scheduleTempId"],
          },
        },
        confidence: { enum: ["high", "review", "uncertain"] },
        evidence: { $ref: "#/$defs/evidence" },
      },
      required: ["type", "scheduleTempIds", "weekdayMappings", "confidence", "evidence"],
    },
    noSchoolRanges: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          id: { type: "string" },
          startDate: { type: "string" },
          endDate: { type: "string" },
          label: { type: "string" },
          type: { type: ["string", "null"] },
          confidence: { enum: ["high", "review", "uncertain"] },
          evidence: { $ref: "#/$defs/evidence" },
        },
        required: ["id", "startDate", "endDate", "label", "type", "confidence", "evidence"],
      },
    },
    specialSchoolDays: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          id: { type: "string" },
          startDate: { type: "string" },
          endDate: { type: "string" },
          label: { type: "string" },
          type: { type: ["string", "null"] },
          scheduleTempId: { type: ["string", "null"] },
          isInstructional: { type: "boolean" },
          confidence: { enum: ["high", "review", "uncertain"] },
          evidence: { $ref: "#/$defs/evidence" },
        },
        required: [
          "id",
          "startDate",
          "endDate",
          "label",
          "type",
          "scheduleTempId",
          "isInstructional",
          "confidence",
          "evidence",
        ],
      },
    },
    informationalDates: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          id: { type: "string" },
          date: { type: "string" },
          label: { type: "string" },
          confidence: { enum: ["high", "review", "uncertain"] },
          evidence: { $ref: "#/$defs/evidence" },
        },
        required: ["id", "date", "label", "confidence", "evidence"],
      },
    },
    legendInterpretation: { type: ["string", "null"] },
    extractionNotes: { type: ["string", "null"] },
    warnings: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          code: { type: "string" },
          message: { type: "string" },
          severity: { enum: ["info", "review", "blocking"] },
        },
        required: ["code", "message", "severity"],
      },
    },
  },
  required: [
    "documentTitle",
    "detectedSchoolName",
    "schoolYearLabel",
    "firstInstructionalDate",
    "lastInstructionalDate",
    "operatingWeekdays",
    "expectedInstructionalDayCount",
    "schoolYearConfidence",
    "detectedSchedules",
    "normalPattern",
    "noSchoolRanges",
    "specialSchoolDays",
    "informationalDates",
    "legendInterpretation",
    "extractionNotes",
    "warnings",
  ],
  $defs: {
    evidence: {
      type: "object",
      additionalProperties: false,
      properties: {
        sourceText: { type: ["string", "null"] },
        page: { type: ["integer", "null"], minimum: 1 },
        explanation: { type: ["string", "null"] },
      },
      required: ["sourceText", "page", "explanation"],
    },
  },
} as const;
