export const AI_CALENDAR_ANALYSIS_VERSION = "calendar-v13-page-selection-v1";
export const AI_CALENDAR_REVIEW_ISSUE_SCHEMA_VERSION = 3;
export const AI_CALENDAR_ISSUE_NORMALIZATION_VERSION = "issue-normalization-v2";
export const AI_CALENDAR_CACHE_SCHEMA_VERSION = "cache-schema-v2";
export const AI_CALENDAR_CACHE_KEY_VERSION = [
  AI_CALENDAR_ANALYSIS_VERSION,
  AI_CALENDAR_CACHE_SCHEMA_VERSION,
  AI_CALENDAR_ISSUE_NORMALIZATION_VERSION,
].join("::");
