"use client";
import {useActionState,useState} from "react";
import type {PlatformSettingsRow,SchoolSetupEmailProvider} from "@/lib/platformSettings";
import type {ProviderConfiguration} from "@/lib/email/schoolSetupProviders.server";
import {INITIAL_SETTINGS_STATE,INITIAL_TEST_EMAIL_STATE} from "./actionState";
import {saveEmailDeliverySettings,sendTestSchoolSetupEmail} from "./actions";
import {initialEmailDeliverySelection,isEmailDeliverySelectionDirty,reconcileEmailDeliverySelection,selectEmailDeliveryProvider} from "./emailDeliverySelection";
import {sundialPrimaryButtonClass} from "@/lib/ui/buttonStyles";
const labels={google_workspace:"Google Workspace",resend:"Resend"} as const;
const descriptions={google_workspace:"Sends through the established mrhcodes.com Google Workspace account as Sundial School Setup <sundialk12@mrhcodes.com>",resend:"Sends through Resend as Sundial School Setup <setup@sundialk12.com>"} as const;
const identities={google_workspace:"Sundial School Setup <sundialk12@mrhcodes.com>",resend:"Sundial School Setup <setup@sundialk12.com>"} as const;
export function EmailDeliveryForm({settings,changedBy,configuration}:{settings:PlatformSettingsRow;changedBy:string;configuration:Record<SchoolSetupEmailProvider,ProviderConfiguration>}){
 const active=settings.school_setup_email_provider;const [selection,setSelection]=useState(()=>initialEmailDeliverySelection(active));const [saveState,saveAction,saving]=useActionState(saveEmailDeliverySettings,INITIAL_SETTINGS_STATE);const [testState,testAction,testing]=useActionState(sendTestSchoolSetupEmail,INITIAL_TEST_EMAIL_STATE);const synchronizedSelection=reconcileEmailDeliverySelection(selection,active);
 if(synchronizedSelection!==selection)setSelection(synchronizedSelection);
 const provider=synchronizedSelection.selected;
 const dirty=isEmailDeliverySelectionDirty(synchronizedSelection);
 return <div className="space-y-8"><dl className="grid gap-4 rounded-xl bg-slate-50 p-5 text-sm dark:bg-slate-900 sm:grid-cols-2"><Info term="Active provider" value={labels[active]}/><Info term="Active From address" value={identities[active]}/><Info term="Reply-To address" value="mrh@mrhcodes.com"/><Info term="Configuration status" value={configuration[active].configured?"Configured":"Not configured"}/><Info term="Last changed" value={settings.school_setup_email_provider_updated_at?new Date(settings.school_setup_email_provider_updated_at).toLocaleString():"Using production default"}/><Info term="Last changed by" value={changedBy}/></dl>
 <form action={saveAction} className="space-y-5" onSubmit={e=>{if(dirty&&!confirm(`Future school setup and administrator invitation emails will be sent through ${labels[provider]}. Existing invitations are not affected.`))e.preventDefault()}}><input type="hidden" name="version" value={saveState.version||settings.version}/><fieldset><legend className="font-bold">Setup invitation provider</legend><div className="mt-3 grid gap-3">{(["google_workspace","resend"] as const).map(value=><label key={value} className="flex gap-3 rounded-xl border border-slate-200 p-4 dark:border-slate-800"><input type="radio" name="school_setup_email_provider" value={value} checked={provider===value} onChange={()=>setSelection(selectEmailDeliveryProvider(synchronizedSelection,value))}/><span><span className="font-semibold">{labels[value]}</span><span className="mt-1 block text-sm text-slate-600 dark:text-slate-300">{descriptions[value]}</span><span className={`mt-2 block text-xs font-bold ${configuration[value].configured?"text-emerald-700":"text-amber-700"}`}>{configuration[value].configured?"Configured":`Not configured — missing ${configuration[value].missing.join(", ")}`}</span></span></label>)}</div></fieldset><Result state={saveState}/><button disabled={saving||!dirty||!configuration[provider].configured} className={sundialPrimaryButtonClass("px-5 py-3")}>{saving?"Saving…":"Save Email Delivery"}</button></form>
 <form action={testAction} className="space-y-4 border-t border-slate-200 pt-6 dark:border-slate-800"><h3 className="font-bold">Send test email</h3><input type="hidden" name="provider" value={provider}/><label className="block text-sm font-semibold">Test recipient email<input name="recipient" type="email" required maxLength={254} className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950"/></label><Result state={testState}/>{testState.providerMessageId&&<p className="break-all text-xs text-slate-500">Provider message ID: {testState.providerMessageId}</p>}<button disabled={testing||!configuration[provider].configured} className={sundialPrimaryButtonClass("px-5 py-3")}>{testing?"Sending…":"Send test email"}</button></form></div>;
}
function Info({term,value}:{term:string;value:string}){return <div><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">{term}</dt><dd className="mt-1 break-words font-medium">{value}</dd></div>}
function Result({state}:{state:{status:string;message?:string}}){return state.message?<p role={state.status==="success"?"status":"alert"} className={`rounded-lg p-3 text-sm ${state.status==="success"?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-900"}`}>{state.message}</p>:null}
