import Link from "next/link";
import { requireSuperAdminAccess } from "@/lib/auth/adminPermissions";
import { getIntegrationHealth } from "@/lib/integrationHealth.server";
import { PLATFORM_FEATURE_KEYS, type PlatformFeatureKey, type PlatformSettingsRow } from "@/lib/platformSettings";
import { DefaultsForm, GeneralForm } from "./SettingsForms";

const tabs=[{key:"general",label:"General"},{key:"defaults",label:"New School Defaults"},{key:"integrations",label:"Integrations"},{key:"audit",label:"Audit History"}] as const;
export default async function PlatformSettingsPage({searchParams}:{searchParams:Promise<{tab?:string;page?:string}>}){
 const {supabase}=await requireSuperAdminAccess(); const query=await searchParams; const tab=tabs.some(t=>t.key===query.tab)?query.tab!:"general"; const page=Math.max(1,Number(query.page)||1); const pageSize=20;
 const [{data:settings,error:settingsError},{data:defaults,error:defaultsError}]=await Promise.all([supabase.from("platform_settings").select("support_email,default_sender_name,support_website_url,support_phone,default_timezone,default_appearance,version,updated_at,updated_by").eq("id",true).single<PlatformSettingsRow>(),supabase.from("platform_feature_defaults").select("feature_key,enabled")]);
 if(settingsError||defaultsError||!settings)return <SettingsFrame tab={tab}><p role="alert" className="rounded-xl bg-red-50 p-5 text-red-800 dark:bg-red-500/10 dark:text-red-200">Platform settings are unavailable. Confirm the platform-settings migration has been applied.</p></SettingsFrame>;
 const features=Object.fromEntries(PLATFORM_FEATURE_KEYS.map(key=>[key,defaults?.find(row=>row.feature_key===key)?.enabled??true])) as Record<PlatformFeatureKey,boolean>;
 let content:React.ReactNode;
 if(tab==="general")content=<section><Heading title="General" description="Sundial-wide support and email display information."/><GeneralForm settings={settings}/><Updated value={settings.updated_at}/></section>;
 else if(tab==="defaults")content=<section><Heading title="New School Defaults" description="Starting values copied into future tenant records."/><DefaultsForm settings={settings} features={features}/><Updated value={settings.updated_at}/></section>;
 else if(tab==="integrations")content=<section><Heading title="Integrations" description="Safe server-side configuration checks. Configured does not mean live provider verification succeeded."/><div className="grid gap-4">{getIntegrationHealth().map(item=><article key={item.name} className="rounded-xl border border-slate-200 p-5 dark:border-slate-800"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">{item.name}</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold dark:bg-slate-800">{item.status}</span></div><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{item.detail}</p>{item.variables&&<p className="mt-2 text-xs text-slate-500">Check: {item.variables.join(", ")}</p>}</article>)}</div></section>;
 else {const from=(page-1)*pageSize;const {data:audits,count,error}=await supabase.from("platform_settings_audit").select("id,section,summary,previous_values,new_values,result_status,created_at,users(first_name)",{count:"exact"}).order("created_at",{ascending:false}).range(from,from+pageSize-1);content=<section><Heading title="Audit History" description="Immutable history of platform-setting changes."/>{error?<p role="alert">Audit history could not be loaded.</p>:!audits?.length?<p className="rounded-xl border border-dashed p-8 text-center text-slate-500">No platform-setting changes yet.</p>:<><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b dark:border-slate-800"><th className="p-3">Date</th><th className="p-3">Actor</th><th className="p-3">Section</th><th className="p-3">Summary</th><th className="p-3">Status</th></tr></thead><tbody>{audits.map((row)=><tr key={row.id} className="border-b dark:border-slate-800"><td className="p-3 whitespace-nowrap">{new Date(row.created_at).toLocaleString()}</td><td className="p-3">{(row.users as unknown as {first_name?:string|null})?.first_name||"SuperAdmin"}</td><td className="p-3 capitalize">{row.section.replaceAll("_"," ")}</td><td className="p-3">{row.summary}</td><td className="p-3 capitalize">{row.result_status}</td></tr>)}</tbody></table></div><nav className="mt-5 flex justify-between"><Link aria-disabled={page===1} className={page===1?"pointer-events-none opacity-40":"font-semibold text-blue-700"} href={`?tab=audit&page=${page-1}`}>Previous</Link><span>Page {page}</span><Link aria-disabled={from+pageSize>=(count||0)} className={from+pageSize>=(count||0)?"pointer-events-none opacity-40":"font-semibold text-blue-700"} href={`?tab=audit&page=${page+1}`}>Next</Link></nav></>}</section>}
 return <SettingsFrame tab={tab}>{content}</SettingsFrame>;
}
function SettingsFrame({tab,children}:{tab:string;children:React.ReactNode}){return <div className="mx-auto max-w-5xl"><div className="mb-8"><p className="text-sm font-bold uppercase tracking-[.18em] text-blue-700 dark:text-blue-300">Platform administration</p><h1 className="mt-2 text-3xl font-bold">Settings</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Sundial-wide configuration for verified SuperAdmins.</p></div><nav aria-label="Settings sections" className="mb-6 flex gap-2 overflow-x-auto border-b border-slate-200 dark:border-slate-800">{tabs.map(item=><Link key={item.key} href={`?tab=${item.key}`} aria-current={tab===item.key?"page":undefined} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-semibold ${tab===item.key?"border-blue-600 text-blue-700 dark:text-blue-300":"border-transparent text-slate-500 hover:text-slate-900 dark:hover:text-white"}`}>{item.label}</Link>)}</nav><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-zinc-950 sm:p-7">{children}</div></div>}
function Heading({title,description}:{title:string;description:string}){return <div className="mb-6"><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{description}</p></div>}
function Updated({value}:{value:string}){return <p className="mt-6 text-xs text-slate-500">Last updated {new Date(value).toLocaleString()}</p>}
