"use client";
import { useActionState, useEffect, useRef, useState } from "react";
import { FEATURE_LABELS, PLATFORM_FEATURE_KEYS, type PlatformFeatureKey, type PlatformSettingsRow } from "@/lib/platformSettings";
import { INITIAL_SETTINGS_STATE, saveGeneralSettings, saveNewSchoolDefaults } from "./actions";
import { sundialPrimaryButtonClass } from "@/lib/ui/buttonStyles";

function useDirtyWarning(){const [dirty,setDirty]=useState(false);useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",before);return()=>window.removeEventListener("beforeunload",before)},[dirty]);return{dirty,setDirty};}
const inputClass="mt-2 w-full rounded-lg border border-slate-300 bg-white px-4 py-3 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-600/20 dark:border-slate-700 dark:bg-slate-950";
function Result({state}:{state:{status:string;message?:string}}){if(!state.message)return null;return <p role={state.status==="success"?"status":"alert"} className={`rounded-lg px-4 py-3 text-sm ${state.status==="success"?"bg-emerald-50 text-emerald-800 dark:bg-emerald-500/10 dark:text-emerald-200":"bg-amber-50 text-amber-900 dark:bg-amber-500/10 dark:text-amber-200"}`}>{state.message}{state.status==="stale"&&<button type="button" onClick={()=>location.reload()} className="ml-2 font-bold underline">Reload</button>}</p>}
export function GeneralForm({settings}:{settings:PlatformSettingsRow}){const [state,action,pending]=useActionState(saveGeneralSettings,INITIAL_SETTINGS_STATE);const {dirty,setDirty}=useDirtyWarning();const submitted=useRef(false);useEffect(()=>{if(state.status==="success"){setDirty(false);submitted.current=false}},[state,setDirty]);return <form action={action} onChange={()=>setDirty(true)} onSubmit={(e)=>{if(submitted.current||pending){e.preventDefault();return}submitted.current=true}} className="space-y-5"><input type="hidden" name="version" value={state.version||settings.version}/><label className="block text-sm font-semibold">Platform name<input value="Sundial" readOnly className={`${inputClass} bg-slate-100 dark:bg-slate-900`}/><span className="mt-1 block text-xs font-normal text-slate-500">Branding is managed in code.</span></label><label className="block text-sm font-semibold">Support email<input name="support_email" type="email" maxLength={254} required defaultValue={settings.support_email} className={inputClass}/></label><label className="block text-sm font-semibold">Default email sender name<input name="default_sender_name" maxLength={80} required defaultValue={settings.default_sender_name} className={inputClass}/></label><label className="block text-sm font-semibold">Support website URL <span className="font-normal text-slate-500">(optional)</span><input name="support_website_url" type="url" maxLength={300} defaultValue={settings.support_website_url||""} className={inputClass}/></label><label className="block text-sm font-semibold">Support phone <span className="font-normal text-slate-500">(optional)</span><input name="support_phone" type="tel" maxLength={40} defaultValue={settings.support_phone||""} className={inputClass}/></label><Result state={state}/><button disabled={pending||!dirty} className={sundialPrimaryButtonClass("px-5 py-3")}>{pending?"Saving…":"Save General Settings"}</button></form>}
export function DefaultsForm({settings,features}:{settings:PlatformSettingsRow;features:Record<PlatformFeatureKey,boolean>}){const [state,action,pending]=useActionState(saveNewSchoolDefaults,INITIAL_SETTINGS_STATE);const {dirty,setDirty}=useDirtyWarning();return <form action={action} onChange={()=>setDirty(true)} onSubmit={(e)=>{if(!confirm("Save these defaults for future schools? Existing schools will not be changed."))e.preventDefault()}} className="space-y-6"><input type="hidden" name="version" value={state.version||settings.version}/><p className="rounded-lg bg-blue-50 p-4 text-sm font-semibold text-blue-900 dark:bg-blue-500/10 dark:text-blue-100">These defaults apply to newly created schools. Existing schools are not changed.</p><label className="block text-sm font-semibold">Default timezone<input name="default_timezone" required maxLength={100} defaultValue={settings.default_timezone} className={inputClass}/><span className="mt-1 block text-xs font-normal text-slate-500">Enter a validated IANA timezone, such as America/Los_Angeles.</span></label><fieldset><legend className="text-sm font-semibold">Default appearance</legend><div className="mt-3 flex flex-wrap gap-4">{["light","dark","system"].map(value=><label key={value} className="flex items-center gap-2 capitalize"><input type="radio" name="default_appearance" value={value} defaultChecked={settings.default_appearance===value}/>{value}</label>)}</div></fieldset><fieldset><legend className="text-sm font-semibold">Feature availability</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{PLATFORM_FEATURE_KEYS.map(key=><label key={key} className="flex items-center justify-between rounded-lg border border-slate-200 p-3 dark:border-slate-800"><span>{FEATURE_LABELS[key]}</span><input type="hidden" name="feature_key" value={key}/><input type="checkbox" name={`feature_${key}`} defaultChecked={features[key]}/></label>)}</div></fieldset><Result state={state}/><button disabled={pending||!dirty} className={sundialPrimaryButtonClass("px-5 py-3")}>{pending?"Saving…":"Save New-School Defaults"}</button></form>}
